import Head from 'next/head'
import Script from 'next/script';
import Navbar from './navbar'

export default function Layout({ activeNav, children }) {
    
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

                <Script
                    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
                    crossorigin="anonymous"
                />

                <Script
                    src="https://code.jquery.com/jquery-3.6.1.min.js"
                />
            
                <Script
                    defer
                    src="https://use.fontawesome.com/releases/v5.1.1/js/all.js"
                    integrity="sha384-BtvRZcyfv4r0x/phJt9Y9HhnN5ur1Z+kZbKVgzVBAlQZX4jvAuImlIz+bG7TS00a"
                    crossorigin="anonymous"
                />
            </Head>
            <main>
                <Navbar activeNav={activeNav}/>
                {children}
            </main>
        </div>
    );
  }