import Head from "next/head";
import Script from "next/script";
import Navbar from "./navbar";

export default function Layout({ activeNav, children }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar activeNav={activeNav} />
        {children}
      </main>
    </div>
  );
}
